version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src/server/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/frontend/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
