version: '3.8'

services:
  certbot:
    container_name: ikpru_certbot
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot:/etc/letsencrypt
    networks:
      - ivankprodru_net

  tarantool:
    container_name: ikpru_tarantool
    image: tarantool/tarantool:2.8
    restart: unless-stopped
    environment:
      TARANTOOL_PORT: ${DB_TARANTOOL_PORT:-3301}
      TARANTOOL_USER_NAME: ${DB_TARANTOOL_USER:-nothing}
      TARANTOOL_USER_PASSWORD: ${DB_TARANTOOL_PASSWORD:-nothing}
    command: tarantool /usr/local/share/tarantool/app.lua
    ports:
      - "${DB_TARANTOOL_PORT:-3301}:${DB_TARANTOOL_PORT:-3301}"
    volumes:
      - ./lib/tarantool:/usr/local/share/tarantool
      - ./data/tarantool:/var/lib/tarantool
    networks:
      - ivankprodru_net

  app:
    container_name: ikpru_app
    build:
      context: .
      args:
        STAGE_MODE: ${STAGE_MODE:-prod}
    image: ivankprod/ivankprodru_app:latest
    restart: on-failure
    env_file:
      - ./build_${STAGE_MODE:-prod}/.env
    command: bash -c "cd ./home/app && ./server"
    ports:
      - "${SERVER_PORT_HTTP:-80}:${SERVER_PORT_HTTP:-80}"
      - "${SERVER_PORT_HTTPS:-443}:${SERVER_PORT_HTTPS:-443}"
    volumes:
      - ./build_${STAGE_MODE:-prod}:/home/app
      - ./data/certbot:/etc/letsencrypt
    networks:
      - ivankprodru_net
    depends_on:
      - certbot
      - tarantool

  prometheus:
    container_name: ikpru_prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: root
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/prometheus.web.yml
      - --web.external-url=https://${SERVER_HOST}/admin/monitor/prometheus/
      - --storage.tsdb.path=/etc/prometheus/data
    volumes:
      - ./data/app_cert.pem:/etc/app_cert/app_cert.pem:ro
      - ./data/app_key.pem:/etc/app_cert/app_key.pem:ro
      - ./data/certbot:/etc/letsencrypt
      - ./data/prometheus_cert:/etc/prometheus/cert
      - ./data/prometheus:/etc/prometheus/data
      - ./lib/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./lib/prometheus/prometheus.web.yml:/etc/prometheus/prometheus.web.yml:ro
    networks:
      - ivankprodru_net
    depends_on:
      - app

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: ikpru_grafana
    volumes:
      - ./data/grafana_cert:/etc/grafana/cert
      - ./data/grafana:/var/lib/grafana
      - ./lib/grafana/provisioning:/etc/grafana/provisioning
      - ./lib/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ivankprodru_net
    depends_on:
      - prometheus

networks:
  ivankprodru_net:
    external: true
    name: ivankprodru_net
