version: '3.8'

services:
  tarantool:
    container_name: ikpru_tarantool
    image: tarantool/tarantool:2.8
    env_file:
      - ./.env
    environment:
      TARANTOOL_PORT: ${DB_TARANTOOL_PORT:-3301}
      TARANTOOL_USER_NAME: ${DB_TARANTOOL_USER:-operator}
      TARANTOOL_USER_PASSWORD: ${DB_TARANTOOL_PASSWORD}
    command: tarantool /usr/local/share/tarantool/app.lua
    ports:
      - "${DB_TARANTOOL_PORT:-3301}:${DB_TARANTOOL_PORT:-3301}"
    volumes:
      - ./tarantool/app:/usr/local/share/tarantool
      - ./tarantool/data:/var/lib/tarantool