version: '3.8'

services:
  certbot:
    container_name: ikpru_certbot
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot:/etc/letsencrypt
    networks:
      - ivankprodru_net

  tarantool:
    container_name: ikpru_tarantool
    image: tarantool/tarantool:2.8
    environment:
      TARANTOOL_PORT: ${DB_TARANTOOL_PORT:-3301}
      TARANTOOL_USER_NAME: ${DB_TARANTOOL_USER:-nothing}
      TARANTOOL_USER_PASSWORD: ${DB_TARANTOOL_PASSWORD:-nothing}
    command: tarantool /usr/local/share/tarantool/app.lua
    ports:
      - "${DB_TARANTOOL_PORT:-3301}:${DB_TARANTOOL_PORT:-3301}"
    volumes:
      - ./tarantool/app:/usr/local/share/tarantool
      - ./tarantool/data:/var/lib/tarantool
    networks:
      - ivankprodru_net

  app:
    container_name: ikpru_app
    build: .
    image: ivankprod/ivankprodru_app
    restart: on-failure
    env_file:
      - ./build_${STAGE_MODE:-prod}/.env
    command: bash -c "cd ./home/app && ./server"
    ports:
      - "${SERVER_PORT_HTTP:-80}:${SERVER_PORT_HTTP:-80}"
      - "${SERVER_PORT_HTTPS:-443}:${SERVER_PORT_HTTPS:-443}"
    volumes:
      - ./build_${STAGE_MODE:-prod}:/home/app
      - ./data/certbot:/etc/letsencrypt
    networks:
      - ivankprodru_net
    links:
      - tarantool:${DB_TARANTOOL_HOST:-tarantool}
      - prometheus:prometheus
    depends_on:
      - certbot
      - tarantool
      - prometheus
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/prometheus.web.yml
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./data/prometheus_cert:/etc/prometheus/cert
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus.web.yml:/etc/prometheus/prometheus.web.yml:ro
    networks:
      - ivankprodru_net

networks:
  ivankprodru_net:
    external: true
    name: ivankprodru_net
