name: CI
on:
  push:
    branches:
      - main

jobs:
  server:
    name: Server
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Go Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: src/server/
          args: -v

      - name: Go Test
        run: |
          cd src/server/
          sudo go test -coverprofile=coverage.out -race -v ./...

      - name: Push Go coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: src/server/coverage.out
          verbose: true

  frontend:
    name: Frontend
    strategy:
      matrix:
        node-version: [ '16' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: JS Lint
        run: |
          cd src/frontend/
          npm ci
          npm run lint

      - name: JS Test
        run: |
          cd src/frontend/
          npm run test

      - name: Push JS coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: src/frontend/src/scripts/coverage/
          verbose: true
