name: Lint and Test
on:
  push:
    branches:
    - main

jobs:
  server:
    name: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: src/server/
          args: -v
          skip-go-installation: true

      - name: go-test
        run: cd src/server/ && sudo go test -coverprofile=coverage.out -race -v ./...
