name: Lint and Test
on:
  push:
    branches:
    - main

jobs:
  server:
    name: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: src/server/
          args: -v
          skip-go-installation: true

      - name: go-test
        run: |
          cd src/server/ && sudo go test -coverprofile=coverage.out -race -v ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: coverage-codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: src/server/coverage.out
          fail_ci_if_error: true
          verbose: true

      - name: coverage.html artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-html
          path: src/server/coverage.html

  frontend:
    name: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: eslint
        run: |
          cd src/frontend/
          npm install
          npm run lint

      - name: jest
        run: |
          cd src/frontend/
          npm run test

      - name: coverage-codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: src/frontend/src/scripts/coverage/
          verbose: true
